version: '3.4'
 
services:
  web:
    image: nginx:latest
    container_name: web
    depends_on:
      - php
    ports:
      - "8000:80"
    volumes:
      - ./www:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: php-mysql
    container_name: php
    volumes:
      - ./www:/var/www/html
    links:
      - db
  db:
    container_name: db
    image: mysql:5.5
    ports:
      - "52000:3306"
    restart: always
    environment:
      MYSQL_DATABASE: compras
      MYSQL_USER: agner
      MYSQL_PASSWORD: agner
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./data:/var/lib/mysql
  admin:
    image: phpmyadmin/phpmyadmin
    container_name: admin
    depends_on:
      - db
    environment:
      - PMA_HOST = db
    ports:
      - 8080:80